### ISSUE TITLE
Transposing with SIMD leads to segfaults

### ISSUE THREAD

**Issue by isaaclegred** [sxs-collaboration/spectre#5110]
# Bug reports:

### Expected behavior:

Computing  a transpose using  `raw_transpose` with doubles should transpose the data.  For the case I looked at the failure was in computation of partial derivatives in GhMhd.

### Current behavior:
A Segfault occurs on some simd call.   According to the traceback from the segfault  the call `_mm256_castpd128_pd256(double __vector(2)) at /home/_SYS_/usr_local/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/avxintrin.h:1473` appears in the stack when it segfaults.

### Environment:
SpECTRE Version: 2023.06.19
Git description: v2023.06.19-2-g2371034
Git branch: develop
Git hash: 2371034
Hostname: wheeler
Host system: Linux-3.10.0-327.36.3.el7.x86_64
Host system version: 3.10.0-327.36.3.el7.x86_64
Host system processor: x86_64
Boost version: 1.65.1
Charm++ version: 7.0.0
CHARM_COMPILER: /usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/bin/charmc
CHARM_SHARED_LIBS: OFF
CHARM_BUILDING_BLOCKS:
CHARM_CC='mpicc '
CHARM_CXX='mpicxx '
CHARM_LD='mpicc '
CHARM_LDXX='mpicxx '
CHARM_CC_FLAGS=' -fPIC -DCMK_GFORTRAN -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -I/usr/local/charm/7.0.0-intelmpi/mpi-\
linux-x86_64-smp-gcc/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector '
CHARM_CXX_FLAGS=' -fPIC -DCMK_GFORTRAN -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -I/usr/local/charm/7.0.0-intelmpi/mpi\
-linux-x86_64-smp-gcc/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -std=gnu++11 '
CHARM_LD_FLAGS=' -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -rdynamic -L/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_6\
4-smp-gcc/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-defaul\
t -lldb-rand -lconverse -lpthread -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /usr/local/c\
harm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib/conv-static.o'
CHARM_LDXX_FLAGS=' -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_REENTRANT -rdynamic -L/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86\
_64-smp-gcc/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-defa\
ult -lldb-rand -lconverse -lpthread -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /usr/local\
/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib/conv-static.o'
CHARMBIN='/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/bin'
CHARMINC='/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/include'
CHARMLIB='/usr/local/charm/7.0.0-intelmpi/mpi-linux-x86_64-smp-gcc/lib'
CHARMLIBSO=''
BLAS_LIBRARIES: /usr/local/openblas/0.2.18/lib/libopenblas.so
LAPACK_LIBRARIES: /usr/local/openblas/0.2.18/lib/libopenblas.so;-lpthread;-lm;-ldl
LIBXSMM version: 1.16.1
Blaze version: 3.8
Google Benchmark found
GSL version: 1.15
HDF5 version: 1.12.2
Catch version: 2.13.3
NumPy version: 1.21.6
CMake version: 3.18.2
CMAKE_CXX_FLAGS: -std=c++1y
CMAKE_CXX_LINK_FLAGS:  -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS:
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS:
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/local/gcc/9.3.0/bin/g++
CMAKE_CXX_COMPILER_VERSION: 9.3.0
CMAKE_C_COMPILER: /usr/local/gcc/9.3.0/bin/gcc
CMAKE_C_COMPILER_VERSION: 9.3.0
CMAKE_Fortran_COMPILER: /usr/local/gcc/9.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 9.3.0
Python version: 3.9.12
# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:

In order to reproduce:  call `EvolveGhValenciaDivCleanTovStar` with the following input file.  The segfault should occur in taking the first time step.   
```
# Distributed under the MIT License.
# See LICENSE.txt for details.

# Executable: EvolveGhValenciaDivCleanTovStar
# Check: execute

---
---
ResourceInfo:
  AvoidGlobalProc0: false

DomainCreator:
  AlignedLattice:
  #   # BlockBounds: [[-20.0, -6.666666666666666, 6.666666666666666, 20.0],
  #   #               [-20.0, -6.666666666666666, 6.666666666666666, 20.0],
  #   #               [-20.0, -6.666666666666666, 6.666666666666666, 20.0]]
  #   # BlockBounds: [[-30.0, -10.666666666666666, 10.666666666666666, 30.0],
  #   #               [-30.0, -10.666666666666666, 10.666666666666666, 30.0],
  #   #               [-30.0, -10.666666666666666, 10.666666666666666, 30.0]]
    BlockBounds: [[-15.0, -5.0, 5.0, 15.0],
                 [-15.0, -5.0, 5.0, 15.0],
              [-15.0, -5.0, 5.0, 15.0]]
    InitialGridPoints: [6, 6, 6]
    # InitialLevels: [4, 4, 4]
    InitialLevels: [3, 3, 3]
    # InitialLevels: [2, 2, 2]
    RefinedLevels: []
    RefinedGridPoints: []
    BlocksToExclude: []
    BoundaryCondition:
      DirichletFreeOutflow:
# Sphere:
#     InnerRadius: 34.6410161514
#     OuterRadius: 100
#     InnerCubeSphericity: 0
#     InitialRefinement: 4
#     InitialGridPoints: [6, 6]
#     UseEquiangularMap: false
#     TimeDependence: None
#     BoundaryCondition:
#       ConstraintPreservingFreeOutflow:
#         Type: ConstraintPreservingPhysical

Evolution:
  InitialTime: 0.0
  InitialTimeStep: 0.075
  TimeStepper:
    Rk3HesthavenSsp:
    # AdamsBashforthN:
    #   Order: 1

AnalyticSolution: &InitialData
  TovStar:
    CentralDensity: .8e-3
    EquationOfState:
      Enthalpy(Enthalpy(Enthalpy(Spectral))):
        ReferenceDensity: 0.001822038675716006
        MinimumDensity: 0.001822038675716006
        MaximumDensity: 0.0034
        TrigScaling: 0.0
        PolynomialCoefficients: [1.2730598378768818, 1.2730598378768818, 0.6365299189384409,
        0.21217663964614697, 0.05304415991153674, 0.01060883198230735, 0.0017681386637178915,
        0.0002525912376739845, 3.157390470924806e-05, 3.5082116343608955e-06]
        SinCoefficients: [0.0]
        CosCoefficients: [0.0]
        TransitionDeltaEpsilon: 0.0
        Enthalpy:
          ReferenceDensity: 0.0011334511674839399
          MinimumDensity: 0.0011334511674839399
          MaximumDensity: 0.001822038675716006
          TrigScaling: 0.0
          PolynomialCoefficients: [1.272585148960061, 0.001]
          SinCoefficients: [0.0]
          CosCoefficients: [0.0]
          TransitionDeltaEpsilon: 0.0
          Enthalpy:
            ReferenceDensity: 0.00022669023349678794
            MinimumDensity: 0.0004533804669935759
            MaximumDensity: 0.0011334511674839399
            TrigScaling: 1.26426988871305
            PolynomialCoefficients: [
              1.0,
              0.08063293075870805,
              4.406887319408924e-26,
              8.177895241388924e-22,
              0.013558242085066733,
              0.004117320982626606,
              9.757362504479485e-26,
              1.5646573325075753e-30,
              0.00016253964205058317]
            SinCoefficients: [
              0.0003763514388305583,
              0.017968749910748837,
              0.008140052979970034,
              -0.003067418379116628,
              -0.0008236601907322793]
            CosCoefficients: [
              -0.01080996024705052,
              -0.003421193490191067,
              0.012325774692378716,
              0.004367136076912163,
              -0.00020374276952538073]
            TransitionDeltaEpsilon: 0.0
            Spectral:
              ReferenceDensity: 4.533804669935759e-05
              ReferencePressure: 9.970647727158039e-08
              Coefficients: [
                 1.2, 0.0, 1.34440187653529, -0.46098357752567365]
              UpperDensity: 0.0004533804669935759

    Coordinates: Schwarzschild

SpatialDiscretization:
  BoundaryCorrection:
    ProductUpwindPenaltyAndRusanov:
      UpwindPenalty:
      Rusanov:
  DiscontinuousGalerkin:
    Formulation: StrongInertial
    Quadrature: GaussLobatto
    Subcell:
      RdmpDelta0: 1.0e-7
      RdmpEpsilon: 1.0e-3
      PerssonExponent: 4.0
      InitialData:
        RdmpDelta0: 1.0e-7
        RdmpEpsilon: 1.0e-3
        PerssonExponent: 4.0
      AlwaysUseSubcells: False
      SubcellToDgReconstructionMethod: DimByDim
      UseHalo: True
      OnlyDgBlocksAndGroups: []
      FiniteDifferenceDerivativeOrder: 2
    TciOptions:
      MinimumValueOfD: 1.0e-20
      MinimumValueOfYe: 1.0e-20
      MinimumValueOfTildeTau: 1.0e-50
      AtmosphereDensity: 1.01e-15
      SafetyFactorForB: 1.0e-12
      MagneticFieldCutoff: DoNotCheckMagneticField
  SubcellSolver:
    Reconstructor:
      MonotonisedCentralPrim:
    FilterOptions:
      SpacetimeDissipation: 0.1


Filtering:
  ExpFilter0:
    Alpha: 36
    HalfPower: 64
    Enable: true
    BlocksToFilter: All

PhaseChangeAndTriggers:

  # - - Slabs:
  #       EvenlySpaced:
  #         Interval: 10
  #         Offset: 0
  #   - - VisitAndReturn(LoadBalancing)

EventsAndTriggers:
  # Set time step based on CLF condition
  - Trigger:
      Slabs:
        Specified:
          Values: [0]
    Events:
      - ChangeSlabSize:
          DelayChange: 0
          StepChoosers:
            - Cfl:
                SafetyFactor: 0.5
  - Trigger:
      Slabs:
        EvenlySpaced:
          Interval: 1
          Offset: 0
    Events:
      - ObserveTimeStep:
            SubfileName: TimeSteps
            PrintTimeToTerminal: True
            ObservePerCore: False
      - ObserveNorms:
          SubfileName: Norms
          TensorsToObserve:
            - Name: RestMassDensity
              NormType: Max
              Components: Individual
  - Trigger:
      Slabs:
        EvenlySpaced:
          Interval: 200
          Offset: 0
    Events:
      - ObserveFields:
          SubfileName: VolumeData
          VariablesToObserve:
            - SpacetimeMetric
            - RestMassDensity
            - Pressure
            - SpatialVelocity
            - LorentzFactor
            - SpecificEnthalpy
            - SpecificInternalEnergy
            - MagneticField
            - ElectronFraction
            - DivergenceCleaningField
            - PointwiseL2Norm(GaugeConstraint)
            - TciStatus
          InterpolateToMesh: None
          CoordinatesFloatingPointType: Float
          FloatingPointTypes: [Float]
          OverrideObservationValue: None
  - Trigger:
      TimeCompares:
        Comparison: GreaterThan
        Value: 500
    Events:
      - Completion
  # Adaptive time stepping
  #
  # Because it is the magnetic field setting the CFL and the grid is
  # static, only run CFL once at the very beginning. From then on we prevent the
  # slab size from increasing and check to make sure we arrive at the final time
  #
  # Note: The choices for time stepping are for Runge-Kutta steppers, not
  #       Adams-Bashforth.
  # - - Times:
  #       Specified:
  #         Values: &FinalTime [10.0]
  #   - - Completion

Observers:
  VolumeFileName: "./GhmhdTovStar"
  ReductionFileName: "./GhmhdTovStar"

EvolutionSystem:
  ValenciaDivClean:
    DampingParameter: 1.0
  GeneralizedHarmonic:
    GaugeCondition:
      AnalyticChristoffel:
        AnalyticPrescription: *InitialData
    # The parameter choices here come from our experience with the Spectral
    # Einstein Code (SpEC). They should be suitable for evolutions of a
    # perturbation of a Kerr-Schild black hole.
    DampingFunctionGamma0:
      GaussianPlusConstant:
        Constant: 0.001
        Amplitude: 0.1
        Width: 14.0
        Center: [0.0, 0.0, 0.0]
    DampingFunctionGamma1:
      GaussianPlusConstant:
        Constant: -0.999
        Amplitude: 0.999
        Width: 90.0 # ! 10 * stellar_radius
        Center: [0.0, 0.0, 0.0]
    DampingFunctionGamma2:
      GaussianPlusConstant:
        Constant: 0.001
        Amplitude: 4.0
        Width: 14.0
        Center: [0.0, 0.0, 0.0]

VariableFixing:
  FixConservatives:
    CutoffD: 1.1e-15
    MinimumValueOfD: 1.0e-15
    CutoffYe: 0.0
    MinimumValueOfYe: 0.0
    SafetyFactorForB: 1.0e-12
    SafetyFactorForS: 1.0e-12
  FixToAtmosphere:
    DensityOfAtmosphere: 1.0e-15
    DensityCutoff: 1.1e-15
    TransitionDensityCutoff: 1.0e-14
    MaxVelocityMagnitude: 1.0e-4

Interpolator:
  DumpVolumeDataOnFailure: false


EventsAndDenseTriggers:

# InterpolationTargets:
#   CenterOfStar:
#     Points:

EventsRunAtCleanup:
  - ObserveFields:
      VariablesToObserve:
        [RestMassDensity, SpecificInternalEnergy, Pressure,
        SpecificEnthalpy, SpatialVelocity, LorentzFactor,
        # MagneticField, DivergenceCleaningField,
        TildeD, TildeTau, TildeS,
        SpacetimeMetric, Pi, Phi,
        Error(RestMassDensity),
        Error(SpacetimeMetric),
        Error(Pi), Error(Phi),
        Error(SpatialVelocity),

        TciStatus
        ]
      SubfileName: FailureVolumeData
      InterpolateToMesh: None
      CoordinatesFloatingPointType: Double
      FloatingPointTypes: [Double]
      OverrideObservationValue: -1
```

**Comment by knelli2** [comment]
I find the same behavior for the single BH executable using the `KerrSchild.yaml` test input file. The seg fault also occurs at the very beginning of the Evolve phase. Likely the first step. I have in my stack trace:

```gdb
#0  0x00007fffed22df50 in (anonymous namespace)::transpose_block<4ul, 2ul> (matrix_transpose=0x58a1260, matrix=0x585ccd8, columns=1250, rows=5)
    at /home/knelli/Documents/research/spectre/src/DataStructures/Transpose.cpp:132
132       const __m256d rows0_1 = _mm256_permute2f128_pd(
```

My env:

```
SpECTRE Version: 2023.06.19
Git description: v2023.04.07-151-g23710349ae
Git branch: develop
Git hash: 23710349ae4b59f7dcffc35ca93ec14b520ad2d4
Hostname: jarrus
Host system: Linux-5.14.0-1057-oem
Host system version: 5.14.0-1057-oem
Host system processor: x86_64
Boost version: 1.71.0
Charm++ version: 7.0.0
CHARM_COMPILER: /home/knelli/tools/charm_7/multicore-linux-x86_64/bin/charmc
CHARM_SHARED_LIBS: ON
CHARM_BUILDING_BLOCKS:
CHARM_CC='gcc'
CHARM_CXX='g++'
CHARM_LD='gcc'
CHARM_LDXX='g++'
CHARM_CC_FLAGS=' -DCMK_GFORTRAN -DCMK_GFORTRAN -D_REENTRANT -I/home/knelli/tools/charm_7/multicore-linux-x86_64/include -D__CHARMC__=1 -fno-stack-protector '
CHARM_CXX_FLAGS=' -DCMK_GFORTRAN -DCMK_GFORTRAN -D_REENTRANT -I/home/knelli/tools/charm_7/multicore-linux-x86_64/include -D__CHARMC__=1 -fno-stack-protector -fno-lifetime-dse -std=gnu++11 '
CHARM_LD_FLAGS=' -D_REENTRANT -rdynamic -Wl,-rpath,/home/knelli/tools/charm_7/multicore-linux-x86_64/lib_so/ -L/home/knelli/tools/charm_7/multicore-linux-x86_64/lib_so -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /home/knelli/tools/charm_7/multicore-linux-x86_64/lib/conv-static.o'
CHARM_LDXX_FLAGS=' -D_REENTRANT -rdynamic -Wl,-rpath,/home/knelli/tools/charm_7/multicore-linux-x86_64/lib_so/ -L/home/knelli/tools/charm_7/multicore-linux-x86_64/lib_so -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -lckqt -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /home/knelli/tools/charm_7/multicore-linux-x86_64/lib/conv-static.o'
CHARMBIN='/home/knelli/tools/charm_7/multicore-linux-x86_64/bin'
CHARMINC='/home/knelli/tools/charm_7/multicore-linux-x86_64/include'
CHARMLIB='/home/knelli/tools/charm_7/multicore-linux-x86_64/lib'
CHARMLIBSO='/home/knelli/tools/charm_7/multicore-linux-x86_64/lib_so'
BLAS_LIBRARIES: /usr/lib/x86_64-linux-gnu/libopenblas.so
LAPACK_LIBRARIES: /usr/lib/x86_64-linux-gnu/libopenblas.so;-lpthread;-lm;-ldl
LIBXSMM version: 1.16.2
Blaze version: 3.8
GSL version: 2.5
HDF5 version: 1.10.4
Catch version: 2.13.7
NumPy version: 1.21.6
CMake version: 3.18.2
CMAKE_CXX_FLAGS: -Werror
CMAKE_CXX_LINK_FLAGS:  -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 10.0.0
CMAKE_C_COMPILER: /usr/bin/clang
CMAKE_C_COMPILER_VERSION: 10.0.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 9.4.0
Python version: 3.8.10
```

**Comment by wthrowe** [comment]
Fixed in #5116.

**Comment by nilsvu** [comment]
I'm still getting segfaults with the default `tests/InputFiles/GeneralizedHarmonic/KerrSchild.yaml` input file on develop:

```
  0. [error handling]
  1. ./bin/EvolveGhSingleBlackHole() [0x2979819] - Resolve source file and line with: addr2line -fCpe ./bin/EvolveGhSingleBlackHole 0x2979819
  2. [error handling]
  3. /usr/lib64/libc.so.6(+0x35670) [0x7ff1abe01670] - Resolve source file and line with: addr2line -fCpe /usr/lib64/libc.so.6 0x35670
  4. detail::transpose_impl(double*, double const*, int, int) in /home/nilsvu/spectre/src/DataStructures/Transpose.cpp:412
  5. void partial_derivatives<brigand::list<gr::Tags::SpacetimeMetric<DataVector, 3ul, Frame::Inertial>, gh::Tags::Pi<DataVector, 3ul, Frame::Inertial>, gh::Tags::Phi<DataVector, 3ul, Frame::Inertial> >, brigand::list<gr::Tags::SpacetimeMetric<DataVector, 3ul, Frame::Inertial>, gh::Tags::Pi<DataVector, 3 [...] ndexType)0>, Tensor_detail::TensorIndexType<3ul, (UpLo)1, Frame::Inertial, (IndexType)0> > > const&) in /home/nilsvu/spectre/src/NumericalAlgorithms/LinearOperators/PartialDerivatives.tpp:220
```

Reopening for now. If I did something wrong then we can close this again.

**Comment by knelli2** [comment]
@nilsvu I don't get this on clang-10 Debug on linux. Was your test on Mac?

**Comment by nilsvu** [comment]
On Wheeler, Release

**Comment by knelli2** [comment]
Just build develop single BH exec on wheeler gcc release and the test input file passed for me.

**Comment by nilsvu** [comment]
It's working now, not sure what I did wrong
